language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
# TODO - add Mocha Unit Test to before scripts

# TODO - add deployment to Heroku
